name: SAST analysis
on: 
    push:
        branches: "master"
jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: getting code
              uses: actions/checkout@v4
            - name: installing dependecies
              run: pip install -r requirements.txt
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v2
              with: 
                languages: python
            - name: Analysis
              uses: github/codeql-action/analyze@v2